import { app } from "electron";
import { EventEmitter } from "events";
import fs from "fs/promises";
import path from "path";
import * as dbus from "dbus-next";
import { DEBUG, debug } from "../debug";
import type { Logger } from "../RemoteLogger";

const SERVICE = "org.exiled.ExiledExchange2";
const OBJECT = "/Tracker";
const IFACE = "org.exiled.ExiledExchange2.Tracker";

function buildKwinScript(shortcuts: string[], activatePoe: boolean): string {
  // Embed the shortcut list as a JSON literal the script can iterate.
  const shortcutsJson = JSON.stringify(shortcuts);
  // When the overlay closes, Wayland won't let the app refocus PoE2 itself, so
  // the KWin script reactivates it on load (only on the resume reload).
  const activateSnippet = activatePoe
    ? "try { workspace.activeWindow = list[i]; } catch (e) {}"
    : "";
  return `// auto-generated by Exiled Exchange 2
const SERVICE = "${SERVICE}";
const OBJECT = "${OBJECT}";
const IFACE = "${IFACE}";

function isPoeWindow(w) {
  if (!w) return false;
  var cap = w.caption || "";
  var cls = (w.resourceClass || "").toLowerCase();
  return cap === "Path of Exile 2" || cls === "steam_app_2694490";
}

function call(method) {
  var args = Array.prototype.slice.call(arguments, 1);
  callDBus.apply(null, [SERVICE, OBJECT, IFACE, method].concat(args));
}

// The EE2 overlay is itself a Wayland window. Wayland forbids a client from
// positioning its own toplevel, so Electron's setBounds(x,y) is ignored and
// KWin parks the overlay wherever it likes (often the wrong monitor). KWin
// scripts CAN move windows, so we mirror PoE2's geometry onto the overlay.
function isOverlayWindow(w) {
  if (!w) return false;
  return (w.resourceClass || "").toLowerCase() === "exiled-exchange-2";
}

var lastPoeGeo = null;

function findOverlay() {
  var l = workspace.windowList ? workspace.windowList() : workspace.clientList();
  for (var i = 0; i < l.length; i++) {
    if (isOverlayWindow(l[i])) return l[i];
  }
  return null;
}

function positionOverlay() {
  if (!lastPoeGeo) return;
  var o = findOverlay();
  if (!o || !o.frameGeometry) return;
  var g = o.frameGeometry;
  if ((g.x | 0) === lastPoeGeo.x && (g.y | 0) === lastPoeGeo.y &&
      (g.width | 0) === lastPoeGeo.width && (g.height | 0) === lastPoeGeo.height) {
    return; // already aligned -- avoids a frameGeometryChanged feedback loop
  }
  o.frameGeometry = {
    x: lastPoeGeo.x, y: lastPoeGeo.y,
    width: lastPoeGeo.width, height: lastPoeGeo.height
  };
}

// Keep the overlay ABOVE only while the user is in the game context (PoE2 or
// an EE2 window focused). Otherwise push it below so it never floats over --
// and block mouse input to -- other apps the user alt-tabs to. A blanket
// keepAbove makes the overlay hijack every other window.
function updateOverlayStacking() {
  var o = findOverlay();
  if (!o) return;
  var aw = workspace.activeWindow;
  var inGame = !!(aw && (isPoeWindow(aw) || isOverlayWindow(aw)));
  o.keepAbove = inGame;
  o.keepBelow = !inGame;
  if (inGame) positionOverlay();
}

function trackOverlay(w) {
  positionOverlay();
  updateOverlayStacking();
  // Re-correct whenever the overlay moves (e.g. Electron re-sets its bounds).
  if (w.frameGeometryChanged) {
    w.frameGeometryChanged.connect(function () { positionOverlay(); });
  }
}

function emitGeometry(w) {
  var g = w.frameGeometry;
  if (!g) return;
  lastPoeGeo = { x: g.x | 0, y: g.y | 0, width: g.width | 0, height: g.height | 0 };
  call("Geometry", lastPoeGeo.x, lastPoeGeo.y, lastPoeGeo.width, lastPoeGeo.height);
  positionOverlay();
}

function trackPoe(w) {
  call("Present", true);
  emitGeometry(w);
  call("Focus", !!w.active);
  if (w.frameGeometryChanged) {
    w.frameGeometryChanged.connect(function () { emitGeometry(w); });
  }
  // Listen for PoE2's own active state changes. This is more reliable
  // than workspace.windowActivated (which fires for ANY window becoming
  // active and can leave us in the wrong state when intermediate windows
  // -- notifications, daemons, our own proxy -- briefly take focus
  // without KWin emitting a clean re-activation for PoE2 afterwards).
  if (w.activeChanged) {
    w.activeChanged.connect(function () {
      call("Focus", !!w.active);
      updateOverlayStacking();
    });
  }
  if (w.closed) {
    w.closed.connect(function () { call("Present", false); });
  }
}

call("Hello", "tracker loaded");

// Inventory pass -- find PoE2 and (if already up) the overlay window.
var list = workspace.windowList ? workspace.windowList() : workspace.clientList();
var foundPoe = false, foundOverlay = false;
for (var i = 0; i < list.length; i++) {
  if (!foundPoe && isPoeWindow(list[i])) { trackPoe(list[i]); ${activateSnippet} foundPoe = true; }
  else if (!foundOverlay && isOverlayWindow(list[i])) { trackOverlay(list[i]); foundOverlay = true; }
}

// PoE2 or the overlay appearing later
var added = workspace.windowAdded || workspace.clientAdded;
if (added) {
  added.connect(function (w) {
    if (isPoeWindow(w)) trackPoe(w);
    else if (isOverlayWindow(w)) trackOverlay(w);
  });
}

// Whenever the active window changes, update overlay stacking so it stays
// above the game but never floats over unrelated apps (console, browser, ...).
if (workspace.windowActivated) {
  workspace.windowActivated.connect(function () { updateOverlayStacking(); });
}

// Focus tracking is done per-PoE-window via w.activeChanged inside
// trackPoe (see comment there for why workspace-level activation events
// proved unreliable).

// Cursor position feed. uiohook doesn't see mousemove while PoE2 owns the
// pointer (KWin doesn't forward to XWayland), and Electron's
// screen.getCursorScreenPoint() returns frozen coords there. KWin's JS
// sandbox has no setInterval / Qt globals, so we hook the workspace's
// cursorPosChanged signal and push live coords to our DBus service.
if (workspace.cursorPosChanged) {
  var lastCursorX = -1;
  var lastCursorY = -1;
  workspace.cursorPosChanged.connect(function () {
    var pos = workspace.cursorPos;
    if (!pos) return;
    var x = pos.x | 0;
    var y = pos.y | 0;
    if (x !== lastCursorX || y !== lastCursorY) {
      lastCursorX = x;
      lastCursorY = y;
      call("CursorPos", x, y);
    }
  });
}

// User-configured hotkeys. KWin's registerShortcut binds at the compositor
// level, which is the only way Ctrl+letter combos make it through under KDE
// Wayland (KWin filters them out of the XWayland pipeline otherwise).
var SHORTCUTS = ${shortcutsJson};
for (var j = 0; j < SHORTCUTS.length; j++) {
  (function (shortcut, idx) {
    registerShortcut(
      "exiled-exchange-2-hk-" + idx,
      "Exiled Exchange 2: " + shortcut,
      shortcut,
      function () { call("Hotkey", shortcut); }
    );
  })(SHORTCUTS[j], j);
}
`;
}

export interface Bounds {
  x: number;
  y: number;
  width: number;
  height: number;
}

export function isKdeWayland(): boolean {
  return (
    process.platform === "linux" &&
    !!process.env.WAYLAND_DISPLAY &&
    (process.env.XDG_CURRENT_DESKTOP || "")
      .toUpperCase()
      .includes("KDE")
  );
}

export class WaylandTracker extends EventEmitter {
  private _bounds: Bounds | null = null;
  private _focused = false;
  private _present = false;
  private _cursor: { x: number; y: number } | null = null;
  private _shortcuts: string[] = [];
  // When pauseShortcuts() is called we stash the active list here and
  // reload the script with no registrations, so KWin stops grabbing
  // those keys at the compositor level. resumeShortcuts() restores.
  // While paused, setShortcuts updates this instead of triggering a
  // reload (we still want the new list applied -- just not until resume).
  private _pausedShortcuts: string[] | null = null;
  private bus: dbus.MessageBus | null = null;
  private scriptPath: string | null = null;
  private _startPromise: Promise<void> | null = null;
  private _scriptId: number | null = null;
  // Serializes script (re)loads. pause/resume/setShortcuts can fire in quick
  // succession (and a resume's PoE-activation can trigger another reload);
  // overlapping load+unload cycles race in KWin and corrupt the global
  // shortcut registration (Shift+Space stops firing after one open/close).
  private _loadChain: Promise<void> = Promise.resolve();

  constructor(private logger: Logger) {
    super();
  }

  get bounds(): Bounds | null {
    return this._bounds;
  }

  get focused(): boolean {
    return this._focused;
  }

  get present(): boolean {
    return this._present;
  }

  get cursor(): { x: number; y: number } | null {
    return this._cursor;
  }

  async start(): Promise<void> {
    if (this._startPromise) return this._startPromise;
    this._startPromise = this._start();
    return this._startPromise;
  }

  private async _start(): Promise<void> {
    try {
      this.bus = dbus.sessionBus();
      debug("[WaylandTracker] connected to session bus");

      // Register our DBus service
      await this.bus.requestName(SERVICE, 0);
      debug("[WaylandTracker] acquired service name", SERVICE);

      // Create the interface
      const iface = this._createInterface();
      this.bus.export(OBJECT, iface);
      debug("[WaylandTracker] exported DBus interface");

      // Write and load the KWin script
      this.scriptPath = path.join(
        app.getPath("userData"),
        "kwin-poe-tracker.js",
      );
      await this._loadKwinScript(this._shortcuts);

      this.logger.write("info [WaylandTracker] started successfully");
    } catch (err) {
      const msg = (err as Error).message;
      this.logger.write(`error [WaylandTracker] failed to start: ${msg}`);
      console.error("[WaylandTracker] start error:", err);
    }
  }

  private _createInterface(): InstanceType<typeof dbus.interface.Interface> {
    const tracker = this;

    // dbus-next uses a class-based approach: subclass Interface, define
    // methods as class members, then use configureMembers to declare their
    // DBus signatures.
    class TrackerInterface extends dbus.interface.Interface {
      Geometry(x: number, y: number, w: number, h: number) {
        tracker._bounds = { x, y, width: w, height: h };
        tracker.emit("geometry", tracker._bounds);
        debug("[WaylandTracker] Geometry", tracker._bounds);
      }
      Focus(focused: boolean) {
        tracker._focused = focused;
        tracker.emit("focus", focused);
        debug("[WaylandTracker] Focus", focused);
      }
      Present(present: boolean) {
        tracker._present = present;
        tracker.emit("present", present);
        debug("[WaylandTracker] Present", present);
      }
      Hello(msg: string) {
        debug("[WaylandTracker] Hello from KWin script:", msg);
        tracker.logger.write(
          `info [WaylandTracker] KWin script says: ${msg}`,
        );
      }
      Hotkey(shortcut: string) {
        debug("[WaylandTracker] Hotkey", shortcut);
        tracker.emit("hotkey", shortcut);
      }
      CursorPos(x: number, y: number) {
        tracker._cursor = { x, y };
        // Don't emit event for every cursor move -- callers poll via getter
      }
    }

    TrackerInterface.configureMembers({
      methods: {
        Geometry: { inSignature: "iiii", outSignature: "" },
        Focus: { inSignature: "b", outSignature: "" },
        Present: { inSignature: "b", outSignature: "" },
        Hello: { inSignature: "s", outSignature: "" },
        Hotkey: { inSignature: "s", outSignature: "" },
        CursorPos: { inSignature: "ii", outSignature: "" },
      },
    });

    return new TrackerInterface(IFACE);
  }

  private async _loadKwinScript(shortcuts: string[], activatePoe = false): Promise<void> {
    // Chain onto any in-flight load so reloads run strictly one-at-a-time.
    const next = this._loadChain
      .catch(() => {})
      .then(() => this._doLoadKwinScript(shortcuts, activatePoe));
    this._loadChain = next.catch(() => {});
    return next;
  }

  private async _doLoadKwinScript(shortcuts: string[], activatePoe = false): Promise<void> {
    if (!this.scriptPath || !this.bus) return;

    // Unload any previously loaded script
    await this._unloadKwinScript();

    // Clear prior shortcut registrations from KGlobalAccel
    await this._clearPriorShortcuts();

    // Write the script
    const script = buildKwinScript(shortcuts, activatePoe);
    await fs.writeFile(this.scriptPath, script, "utf-8");
    debug("[WaylandTracker] wrote KWin script to", this.scriptPath);

    try {
      const scripting = (
        await this.bus.getProxyObject("org.kde.KWin", "/Scripting")
      ).getInterface("org.kde.kwin.Scripting");

      const loadOnce = async (): Promise<number | null> => {
        // KWin processes unloadScript ASYNCHRONOUSLY. If we call loadScript
        // while the previous script is still loaded under the same plugin
        // name, KWin returns -1. Wait until KWin confirms it's gone.
        for (let i = 0; i < 40; i++) {
          const loaded = await scripting
            .isScriptLoaded("exiled-exchange-2-tracker")
            .catch(() => false);
          if (!loaded) break;
          await new Promise((r) => setTimeout(r, 50));
        }
        // loadScript is overloaded (loadScript(s) and loadScript(s,s)).
        // dbus-next can't disambiguate overloads and binds the 1-arg form, so
        // a proxy call with two args fails with "Expected 1 body elements for
        // signature 's' (got 2)". Call it directly with an explicit 'ss'
        // signature to pass both arguments.
        const reply = await this.bus!.call(
          new dbus.Message({
            destination: "org.kde.KWin",
            path: "/Scripting",
            interface: "org.kde.kwin.Scripting",
            member: "loadScript",
            signature: "ss",
            body: [this.scriptPath!, "exiled-exchange-2-tracker"],
          }),
        );
        return reply?.body?.[0] ?? null;
      };

      let id = await loadOnce();
      // -1 means KWin still saw the script as loaded (lost the unload race).
      // Force another unload and retry once.
      if (id == null || id < 0) {
        await this._unloadKwinScript();
        id = await loadOnce();
      }
      this._scriptId = id;
      debug("[WaylandTracker] loaded KWin script, id =", this._scriptId);

      if (this._scriptId != null && this._scriptId >= 0) {
        // Get the script object and call run()
        const scriptObj = await this.bus.getProxyObject(
          "org.kde.KWin",
          `/Scripting/Script${this._scriptId}`,
        );
        const scriptIface = scriptObj.getInterface(
          "org.kde.kwin.Script",
        );
        await scriptIface.run();
        debug("[WaylandTracker] KWin script running");
      } else {
        this.logger.write(
          "error [WaylandTracker] loadScript returned invalid id; tracker not running",
        );
      }
    } catch (err) {
      const msg = (err as Error).message;
      this.logger.write(
        `error [WaylandTracker] failed to load KWin script: ${msg}`,
      );
      console.error("[WaylandTracker] KWin script load error:", err);
    }
  }

  private async _unloadKwinScript(): Promise<void> {
    // Note: do NOT guard on this._scriptId here. A fresh process has
    // _scriptId == null but a previous (crashed/killed) session may have
    // left its script loaded in KWin under the same plugin name, which makes
    // the next loadScript return -1. Always attempt unload-by-name so we
    // start from a clean slate.
    if (!this.bus) return;

    try {
      const kwinObj = await this.bus.getProxyObject(
        "org.kde.KWin",
        "/Scripting",
      );
      const scripting = kwinObj.getInterface("org.kde.kwin.Scripting");
      await scripting.unloadScript("exiled-exchange-2-tracker");
      debug("[WaylandTracker] unloaded KWin script");
    } catch (err) {
      debug("[WaylandTracker] unload error (non-fatal):", (err as Error).message);
    }
    this._scriptId = null;
  }

  private async _clearPriorShortcuts(): Promise<void> {
    if (!this.bus) return;

    try {
      const kgaObj = await this.bus.getProxyObject(
        "org.kde.kglobalaccel",
        "/kglobalaccel",
      );
      const kga = kgaObj.getInterface("org.kde.KGlobalAccel");

      // Get all action names and unregister exiled-exchange-2-* ones
      // The interface uses component + action naming; we need to clean up
      // stale registrations that survive across process restarts.
      try {
        const actions: string[][] = await kga.allActionsForComponent("kwin");
        for (const action of actions) {
          const actionName = action[0];
          if (
            actionName &&
            actionName.startsWith("exiled-exchange-2-")
          ) {
            try {
              await kga.unregister("kwin", actionName);
              debug(
                "[WaylandTracker] unregistered stale shortcut:",
                actionName,
              );
            } catch {
              // ignore individual unregister failures
            }
          }
        }
      } catch {
        // allActionsForComponent may not be available on all KDE versions;
        // the script reload still works, the stale shortcuts just linger
        // until next login.
        debug("[WaylandTracker] could not enumerate KGlobalAccel actions");
      }
    } catch (err) {
      debug(
        "[WaylandTracker] clearPriorShortcuts error (non-fatal):",
        (err as Error).message,
      );
    }
  }

  async setShortcuts(shortcuts: string[]): Promise<void> {
    // Wait for start() to complete before doing anything
    if (this._startPromise) await this._startPromise;

    if (this._pausedShortcuts !== null) {
      // Paused: stash the new list for when we resume
      this._pausedShortcuts = shortcuts;
      this._shortcuts = shortcuts;
      return;
    }

    this._shortcuts = shortcuts;
    await this._loadKwinScript(shortcuts);
  }

  async pauseShortcuts(): Promise<void> {
    if (this._pausedShortcuts !== null) return; // already paused
    this._pausedShortcuts = this._shortcuts;
    debug("[WaylandTracker] pausing shortcuts");
    await this._loadKwinScript([]);
  }

  async resumeShortcuts(): Promise<void> {
    if (this._pausedShortcuts === null) return; // not paused
    const shortcuts = this._pausedShortcuts;
    this._pausedShortcuts = null;
    debug("[WaylandTracker] resuming shortcuts");
    await this._loadKwinScript(shortcuts, true);
  }

  onHotkey(cb: (shortcut: string) => void): void {
    this.on("hotkey", cb);
  }
}
