name: Build

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'docs/**'
      - README.md

jobs:
  renderer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - run: npm ci
      working-directory: ./renderer
    - run: npm run make-index-files
      working-directory: ./renderer
    - run: npm run lint
      working-directory: ./renderer
    - run: npm run build
      working-directory: ./renderer
    - uses: actions/upload-artifact@v7
      with:
        name: renderer-dist
        path: ./renderer/dist
        retention-days: 1

  package:
    needs: renderer
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - uses: actions/download-artifact@v8
      with:
        name: renderer-dist
        path: ./renderer/dist
    - name: Install native dependencies
      run: sudo apt-get update && sudo apt-get install -y ydotool wl-clipboard
    - run: npm ci
      working-directory: ./main
    - run: npm run build
      working-directory: ./main
    - run: npm run package "--" -p onTagOrDraft
      working-directory: ./main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Hash
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: cat ./main/dist/latest-linux.yml
